apiVersion: v1
kind: Service
metadata:
  name: {{ include "pump.fullname" . }}
  labels:
    {{- include "pump.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pump.selectorLabels" . | nindent 4 }}
  ports:
    - name: opc-tcp
      port: {{ .Values.service.port }}
      targetPort: opc-tcp
      protocol: TCP
